### ISSUE TITLE
Register `suggestion-bot` as a GitHub action

### ISSUE THREAD

**Issue by jneeven** [tido64/suggestion-bot#279]
Hi, thanks for this awesome tool! I wish I had found this several years earlier.

One suggestion for improvement:
Currently, I have to run `yarn add ...`, check in a bunch of package files to my repo and explicitly run `yarn` in the GitHub action before running the final command that does all the work. It would be great if `suggestion-bot` itself could be registered as a GitHub action (e.g. like the one that installs NodeJS), taking care of all this behind the scenes. It could just take some input command that produces the diff.

Unfortunately at this time I don't think I'll be able to contribute this feature myself, but at least now the idea is here.

**Comment by jneeven** [comment]
Never mind, there is a much easier solution:
```yaml
      - name: Format code
        run: .github/format_code.sh

      - name: Make code suggestions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git diff --unified=0 --no-color | npx suggestion-bot
```

This is all that's necessary. It won't generate any lock files etc.
